# Generated by Django 5.2 on 2025-04-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_class', '0002_alter_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
